export enum ACTION_TYPES {
    FETCH_CATEGORIES_START="@@CATEGORIES/FETCH_CATEGORIES_START",
    FETCH_CATEGORIES_SUCCESS= "@@CATEGORIES/FETCH_CATEGORIES_SUCCESS",
    FETCH_CATEGORIES_ERROR= "@@CATEGORIES/FETCH_CATEGORIES_ERROR",
}