export enum ACTION_TYPES {
    FETCH_PRODUCTS_START="@@PRODUCTS/FETCH_PRODUCTS_START",
    FETCH_PRODUCTS_SUCCESS="@@PRODUCTS/FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_ERROR="@@PRODUCTS/FETCH_PRODUCTS_ERROR",
}