export enum ACTIONS_TYPE {
    TOGGLE_CART_HIDDEN="@@CART/TOGGLE_CART_HIDDEN",
    ADD_CART_ITEM="@@CART/ADD_CART_ITEM",
    CLEAR_ITEM_FROM_CART="@@CART/CLEAR_ITEM_FROM_CART",
    ADD_ITEM="@@CART/ADD_ITEM",
    REMOVE_ITEM="@@CART/REMOVE_ITEM",
    REMOVE_ALL_ITEMS= "@@CART/REMOVE_ALL_ITEMS",
    CLEAR_CART= '@@CART/CLEAR_CART',
}